### ISSUE TITLE
8012: STATUS_ENDPOINT_IO_ERROR

### ISSUE THREAD

**Issue by OmiWakode** [Cheeseball-Developers/project-circles#71]
This error occurs every time one device tries to requestConnection to the host. The host's side onConnectionInit has a problem, it is not invoking.

**Comment by abhishekUpmanyu** [comment]
Please provide steps to reproduce this error

**Comment by OmiWakode** [comment]
> Please provide steps to reproduce this error

It occurs randomly on one of the phone advertising for connections. I am not sure how to exactly reproduce this. This error occurs few times when i try to advertise. Also heavy radio operations like discovering is already stopped, and the two devices are close enough too.

**Comment by abhishekUpmanyu** [comment]
This bug was fixed in an earlier update, I'm closing the issue
